order:
  pay-timeout-seconds: 120
  create-frequency-seconds: 10
  desc: "订单支付超时时长为 ${order.pay-timeout-seconds} 秒，订单创建频率为 ${order.create-frequency-seconds} 秒"
spring:
  application:
    name: demo-application
  profiles:
    active: uat
    # 配置文件上传大小限制
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
    # redis 配置
  redis:
    # 地址
    host: 116.205.230.136
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s

minio:
  endpoint: http://116.205.230.136:9000
  accessKey: admin
  secretKey: password
  bucketName: yyk #存储桶名称
  port: 9000
